### ISSUE TITLE
Improving the diversity of the list

### ISSUE THREAD

**Issue by JamesMilnerUK** [jkup/awesome-personal-blogs#14]
Firstly, it's great this exists! However, looking at the list, there's not much diversity in terms of the authors. It would be great to feature a more individuals from underrepresented groups. How can we make this happen?

**Comment by jkup** [comment]
@JamesMilnerUK Thanks so much for bringing this up! I definitely noticed that last night when I put the list together D: let's brainstorm anything we can do. I have one idea which is going through the replies to this tweet and adding all of these myself! https://twitter.com/dan_abramov/status/1066851414213894144

**Comment by jkup** [comment]
I added everyone I could find from that list!
