### ISSUE TITLE
Machine parseable blog list

### ISSUE THREAD

**Issue by hugmanrique** [jkup/awesome-personal-blogs#30]
On #7, bilgint1500 sorted the blog list alphabetically by hand. A better way to do this automatically would be to create a source JSON file and a Node.js/Python/whatever script that ordered the entries alphabetically.

This would also give others the possibility of retrieving the raw JSON data for custom UIs, RSS feeds...

_Originally posted by @hugmanrique in https://github.com/jkup/awesome-personal-blogs/pull/7#issuecomment-471967920_

**Comment by aletaschner** [comment]
If that's the case, I think a few other fields should be added in order to classify and filter the entries.

**Comment by speckz** [comment]
OPML, please.

**Comment by jkup** [comment]
This is really interesting! Would you mind if we move the discussion to #43 to all get on the same page? I really like the idea of having a format people can import into their favorite tools!
