### ISSUE TITLE
What should the rules be?

### ISSUE THREAD

**Issue by jkup** [jkup/awesome-personal-blogs#42]
Hello all!

Wow this project really took off! One thing I'd love feedback on is what the rules should be for qualification on the list?

1. Should we allow things like Medium pages or only personal domains?
2. If someone has a company site where they blog, should we allow that?
3. What about non-tech blogs?

**Comment by Krizzu** [comment]
Hey @jkup, thanks for this great initiative.

In my opinion:

1. Medium has tendency to put blogs behind paywall (if author opts in), but I can imagine there're a lot of great bloggers there, so it'd be a shame to not include that.

2. Same as above, shame to lose a good content.

3. Our industry is not only about tech - other skills are also highly valuable.

**Comment by misa527528** [comment]
Hey@jkup , the language of current list is just English, will other languages be accepted😳

**Comment by jkup** [comment]
@misa527528 yes of course! There are already a handful of non-english blogs on the list. I'm going to add a field for "language" and "topics covered" as soon as possible.
