### ISSUE TITLE
What should the list look like?

### ISSUE THREAD

**Issue by jkup** [jkup/awesome-personal-blogs#43]
Hey @fjoshuajr @lipis @hugmanrique @aletaschner

All of you submitted awesome ideas for what the list should look like! PRs were coming in so fast yesterday it kind of got lost in the shuffle so I was hoping to move the conversation into a single thread.

My thinking was:

1. Make it a Markdown table
2. Maybe a separate table for each letter of the alphabet?
3. Add at least a field for what subjects the person talks about

How does that sound? Should we do something different? Hope you don't mind but I'm gonna close the other issues in favor of discussing it all in here!

Thanks!

**Comment by fjoshuajr** [comment]
Sounds good. Based on the previous PR's, something like this?

# A

| Blog | Areas of Interest |                                  
| ---- | ----------------- |
| [Adam C. Conrad](https://userinterfacing.com/) | Frontend, UI, UX |                                             |
| [Adam Rackis](https://adamrackis.dev/) | |                                           |
| [Angie Jones](http://angiejones.tech/)                      |          |                                              |
| [Angus Croll](https://javascriptweblog.wordpress.com/)      |          |                                              |
| [Aditya Rohilla](https://adityarohilla.com/blog/)           |          |                                              |
| [Ali Spittel](https://dev.to/aspittel)                      |          |                                              |
| [Amit Merchant](https://www.amitmerchant.com/)              |          |                                              |
| [Andy Bell](https://andy-bell.design/)                      |          |                                              |
| [Anton Medvedev](https://medv.io)                           |          |                                              |
| [Antonin Januska](https://antjanus.com/)                    |          |                                              |

**Comment by colinrcummings** [comment]
It might be a good idea to have a predefined key for "Areas of Interest" so it doesn't get unwieldy.

**Comment by lipis** [comment]
I would say area of interest/background something about the author and the description of the blog (as it was already [recommended](https://github.com/jkup/awesome-personal-blogs/issues/17#issuecomment-472654099), we can get this info from the open graph).

Not sure if it makes sense to split them in groups as most people I would assume will just try to `cmd+F` (or `ctrl+F`) to find the desired keyword or name.. Also there is a question if we should split them by first name or last :)

**Comment by aletaschner** [comment]
In my humble opinion it is uglier with tables, I like the [awesome-electron](https://github.com/sindresorhus/awesome-electron) kind of way.

I agree with the sorting because as the list grows it would become a big mess without sorting.

And about descriptions / area of interest seems like a good idea to have both if possible.

**Comment by lipis** [comment]
On a second thought.. with prettified tables every diff might be ugly..

**Comment by pauloxnet** [comment]
Maybe when can use a definition list for every letter.

--- 

# Awesome Personal Blogs [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)

> A delightful list of personal tech blogs

## Personal Blogs

### TOC

- [A](#a)
- ...
- [P](#p)



### A

<dl>
  <dt><a href="https://userinterfacing.com/">Adam C. Conrad</a></dt>
  <dd>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</dd>
  <dt><a href="https://adamrackis.dev/">Adam Rackis</a></dt>
  <dd>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</dd>
</dl>

### ...

...

### P

<dl>
  <dt><a href="https://www.paulox.net/">Paolo Melchiorre</a></dt>
  <dd>#Python developer #Django contributor #Conference speaker #Remote worker #GNULinux user #FreeSoftware advocate</dd>
  <dt><a href="https://www.pcmaffey.com/">PC Maffey</a></dt>
  <dd>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</dd>
</dl>

**Comment by SandroMiguel** [comment]
What about the language of the blog? My blog is in Portuguese. Can I also add it to the list?

**Comment by antonmedv** [comment]
What about adding screenshots? Will be cool.

**Comment by evangrim** [comment]
One index sorted by name and another sorted by topic?

**Comment by lipis** [comment]
Let's just not make it Yahoo! directory.. suppose to be a _curated_ list of blogs.. 

https://s3.amazonaws.com/images.seroundtable.com/yahoo-directory-1997-1411992701.png

**Comment by antonmedv** [comment]
Definitely add short info about blog and what author is writing about (Like tags: php, nodejs, devops, etc).

**Comment by egomadking** [comment]
I would also include company currently (and team if applicable)working for.

**Comment by thee-engineer** [comment]
How about having multiple .md files, each one covering a different approach in ordering the blogs (eg, based on: tags, language, companies, etc) and on the main page we can have a directory of letters, and alphabetically sorted blogs (by blog name or author, depending on the blog type). Each blog should be accompanied by a short description (impose a min and max char limit). This way we keep things nice and clean, people can easily find the blogs that could potentially interest them the most without creating a monolithical table with tens of columns. A nice extra feature could be a "top picks" selection at the top of the README, this could rotate some interesting or "hot" blogs (could be hard to determine what goes there).

**Comment by lipis** [comment]
What is needed is to have a JSON file with info (name, link, company, area, description, etc) and then a script that will generate the md file or multiple files. People will update only the JSON and the bots will be updating the md files on every PR.

**Comment by thee-engineer** [comment]
```json
{
    "name": "Awesome Blog Name",
    "owner": "Jon Doe",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "url": "https://example.com",
    "tags": ["low level", "backend", "security"],
    "company": "Lorem Ipsum Inc.",
    "languages": ["en", "ro"]
}
```

Anybody wish to extend on this? We should also enforce a limit on the number of tags and description.
If we have this format we can then generate the .md's for each filtering (@lipis) category or even have a static generated website using Jekyll.

Opinions @jkup ?

**Comment by chrisaldrich** [comment]
<p>I've seen a few somewhat similar directory projects like this that might have some useful ux/ui/design ideas:</p>
<ul>
	<li><a href="https://personalsit.es/" target="_blank" rel="noopener">https://personalsit.es/</a> with repo at: <a href="https://github.com/andybelldesign/personalsit.es" target="_blank" rel="noopener">https://github.com/andybelldesign/personalsit.es</a></li>
	<li><a href="https://nownownow.com/" target="_blank" rel="noopener">https://nownownow.com/</a></li>
</ul>
<p>For additional metadata, one could run a microformats parser on the homepages of these sites and return social media presences in other locations using XFN's <code>rel="me"</code> set up. Something like this is done by Jeremy Keith on his <a href="https://huffduffer.com" target="_blank" rel="noopener">Huffduffer.com</a> service where one signs up and inputs one's website. His service then doesn't need to ask for Twitter, Facebook, or Github handles explicitly. Instead it relies on the service going to the homepage listed and pulling out the <code>rel="me"</code> values and doing it automatically on their behalf. Since many web platforms have this microformat value it can make the data acquisition easier and less manual in many cases.</p>
<ul>
	<li>Example: <a href="https://huffduffer.com/adactio" target="_blank" rel="noopener">Jeremy's profile</a> (see the "Elsewhere" section and compare it to <a href="http://adactio.com" target="_blank" rel="noopener">his personal website</a>.)</li>
	<li>Details about some of the implementation:

<ul>
	<li><a href="https://adactio.com/journal/1533" target="_blank" rel="noopener">https://adactio.com/journal/1533</a></li>
	<li>Relevant section from book <em><a href="https://books.google.com/books?id=6D0Vgo7o7vkC&amp;pg=PA60&amp;lpg=PA60&amp;dq=huffduffer+profile&amp;source=bl&amp;ots=7rj32aKDBc&amp;sig=ACfU3U1yeDCIEPScBIxszIHaAV0aUU3dkw&amp;hl=en&amp;sa=X&amp;ved=2ahUKEwiYiqPhkqHhAhUPPN8KHf5HCPM4ChDoATAAegQICRAB#v=onepage&amp;q=huffduffer%20profile&amp;f=false" target="_blank" rel="noopener">Microformats Made Simple</a></em></li>
	<li><a href="https://indieweb.org/rel-me" target="_blank" rel="noopener">https://indieweb.org/rel-me</a></li>
	<li><a href="http://microformats.org/wiki/rel-me" target="_blank" rel="noopener">http://microformats.org/wiki/rel-me</a></li>
</ul>
</li>
</ul>

(Originally posted at https://boffosocko.com/2019/03/27/55747316/)

**Comment by jkup** [comment]
Hey! So sorry I've been away and missing out on this great conversation. I promise I'll catch up in the next day but these ideas are great!
