### ISSUE TITLE
Made a simple web app version of the list. Complete with an API!

### ISSUE THREAD

**Issue by WalkerFrederick** [jkup/awesome-personal-blogs#86]
idk if this is something anyone asked for but I made it.

https://awesome-personal-blogs.herokuapp.com/

and then there is an API if you want to use it.

https://awesome-personal-blogs.herokuapp.com/blogs

It does some web scraping to grab the list from the readme. In addition it also adds the favicon to the link. 

[Check out the repo!](https://github.com/WalkerFrederick/awesome-personal-blogs-site)

let me know what you think! Thanks.

**Comment by farskid** [comment]
LGTML 👍 Nice job @WalkerFrederick

**Comment by jkup** [comment]
I think it would be great to keep this repo a simple readme.me. If you want to link your herokuapp to the top feel free to make a PR it's really cool. Similarly @farskid if you end up making a site too and want to link it i'd love that! But for now let's just keep this a simple MD file. Thanks all!
