### ISSUE TITLE
Mike Behnke is listed wrong

### ISSUE THREAD

**Issue by nitinthewiz** [jkup/awesome-personal-blogs#91]
The site for Mike Behnke is listed as http://kgrz.io

The site seems to actually belong to one Kashyap Kondamudi 

Is the data here wikipedia style democratic and I can edit it (and send a PR) or would you prefer an open issue to track and ask for changes?

**Comment by nitinthewiz** [comment]
I've just submitted a PR with an OPML file of the feeds I could find. About 27 sites didn't have feeds. The rest did. In the OPML, I've listed the kgrz.io site as correctly belonging to Kashyap Kondamudi. I don't know what Mike Behnke's site is.

**Comment by jkup** [comment]
Hey! Thanks! If the site is wrong, a PR would be great. As for the OPML, let's just keep it a simple readme.md for now but thanks!
